### ISSUE TITLE
BigInteger parser

### ISSUE THREAD

**Issue by wrandelshofer** [wrandelshofer/FastDoubleParser#30]
@wrandelshofer I'm using v0.5.2 and have found that `JavaBigIntegerParser,parseBigInteger(CharSequence str)` accepts hex values like "AAAA" but `new BigInteger(String)` throws a NumberFormatException with "AAAA".

Would it be possible to support being able to disable hex support?

_Originally posted by @pjfanning in https://github.com/wrandelshofer/FastDoubleParser/issues/24#issuecomment-1332929009_

**Comment by wrandelshofer** [comment]
The JavaBigIntegerParser is experimental.

Right now, it parses a super set of the syntax supported by [BigInteger(String)](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/math/BigInteger.html#%3Cinit%3E(java.lang.String)).

What this parser eventually will do, is constructing a BigInteger from an [`IntegerLiteral`](https://docs.oracle.com/javase/specs/jls/se19/html/jls-3.html#jls-3.10.1) but without support for the '_' characters.
The syntax of `IntegerLiteral` is a bit unfortunate, because a leading zero means that the input is an octal number.

I am also looking at the API of BigInt in EcmaScript. There we have function [StringToBigInt(str)](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/math/BigInteger.html#%3Cinit%3E(java.lang.String)) which has a nice syntax: [StringIntegerLiteral Grammar](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/math/BigInteger.html#%3Cinit%3E(java.lang.String)).

I am not sure about the API design yet. I am currently going for the following API:

```
public class JavaBigIntegerParser {
/** Compatible with BigInteger(String) constructor: */
public static BigInteger parseBigInteger(...); 
public static BigInteger parallelParseBigInteger(...);

/** Compatible with IntegerLiteral except '_' character: */
public static BigInteger parseIntegerLiteral(...); 
public static BigInteger parallelParseIntegerLiteral(...);
}

public class EcmaScriptBigIntegerParser {
/** Compatible with StringToBigInt(str) function: */
public static BigInteger parseStringIntegerLiteral (...); 
public static BigInteger parallelParseStringIntegerLiteral (...);
}
```

I think, for consistency I should rename the methods in the existing JSonDoubleParser from `parseDouble` to `parseNumber`:

```
public class JsonDoubleParser {
/** Compatible with Json `number`: */
public static double parseNumber(...); 
}
```

**Comment by wrandelshofer** [comment]
Actually, this is bug. 
JavaBigIntegerParser,parseBigInteger("AAAA") does not parse the input as a hex number. It returns a bogus value.
The code should throw a NumberFormatException in this case.

**Comment by wrandelshofer** [comment]
I have fixed 'parsing of "AAAA" input string without throwing a NumberFormatException' in release 0.5.3.

**Comment by pjfanning** [comment]
@wrandelshofer I upgraded jackson-core to use v0.5.3 but still see the issue where a string that repeats 1500 A chars does not have a NumberFormatException in JavaBigIntegerParser,parseBigInteger.

The issue can be seen in https://github.com/pjfanning/jackson-core/tree/fastdoubleparser-0.5.3 (run tests with `./mvnw test`.

**Comment by wrandelshofer** [comment]
I have released v0.5.4 now.
